### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by fukemy** [ken107/janus-videoroom-js#1]
Hi, I want to ask does this library support React Native? Thanks alots

**Comment by ken107** [comment]
This library is just a thin abstraction layer on top of janus.js.  And as far as I understand janus.js is for web only.

To use Janus in mobile app, you'll need to use one of the SDKs.  This thread is a good starting point: https://groups.google.com/g/meetecho-janus/c/TbDK2Vwqz60/m/tjn46XVVCwAJ

**Comment by fukemy** [comment]
got it, thanks you
